# Generated by Django 6.0.6 on 2026-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ChatBot Setting',
                'verbose_name_plural': 'ChatBot Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('response_text', models.TextField()),
                ('matched_sources_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('added_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scraper Log',
                'verbose_name_plural': 'Scraper Logs',
                'ordering': ['-start_time'],
            },
        ),
    ]
